# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
# command to run tests
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t usermgmt .
      - docker images
      - docker tag usermgmt $DOCKER_USERNAME/usermgmt-$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/usermgmt-$TRAVIS_BUILD_NUMBER
    - stage: unit-test
      script:
      - nosetests
    - stage: code-coverage
      script:
      - coverage run -m pytest  
after_success:
  - coverage report --omit=*lib* 
  - bash <(curl -s https://codecov.io/bash)
