{
 "title": "usermanagemnt-APM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "url", "query": "flask_request_count" },
   { "name": "http_status", "query": "flask_request_count" },
   { "name": "method", "query": "flask_request_count" }
  ]
 },
 "panels": [
  { "title": "Process stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max procs fd",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_max_fds{job=\"usermgmt\"}\t"
    }
   ]
  },
  {
   "title": "Current procs FD",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{job=\"usermgmt\"}"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count[5m])) by (method)\n"
    }
   ]
  },
  {
   "title": "request_latency_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_request_latency_seconds_sum\n"
    }
   ]
  },
  {
   "title": "2xx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"2.*\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "2xx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"2.*\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "4xx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"4.*\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "5xx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"5.*\"}[1m])) by (http_status)\n"
    }
   ]
  },
  { "title": "Api based", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "2xx RPS on [[url]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"2.*\",endpoint=\"[[url]]\",method=\"[[method]]\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "3xx RPS on [[url]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"3.*\",endpoint=\"[[url]]\",method=\"[[method]]\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "4xx RPS on [[url]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"4.*\",endpoint=\"[[url]]\",method=\"[[method]]\"}[1m])) by (http_status)\n"
    }
   ]
  },
  {
   "title": "5xx RPS on [[url]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_request_count{http_status=~\"2.*\",endpoint=\"[[url]]\",method=\"[[method]]\"}[1m])) by (http_status)\n"
    }
   ]
  }
 ]
}